apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9042
      protocol: TCP
      targetPort: 9042
  selector:
    app: cassandra

# service automatically created by k8 plugin for pcs-cassandra
#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kubectl.kubernetes.io/last-applied-configuration: |
#      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":null,"name":"pcs-cassandra","namespace":"pcs-stubbed-functional"},"spec":{"ports":[{"name":"http","port":9042,"protocol":"TCP","targetPort":9042}],"selector":{"app":"cassandra"},"type":"ClusterIP"}}
#  creationTimestamp: "2021-12-09T18:01:12Z"
#  name: pcs-cassandra
#  namespace: pcs-stubbed-functional
#  resourceVersion: "599268109"
#  selfLink: /api/v1/namespaces/pcs-stubbed-functional/services/pcs-cassandra
#  uid: d2b83fc3-1fc8-4d42-80c8-c350787b3faa
#spec:
#  clusterIP: 10.254.80.148
#  ports:
#    - name: http
#      port: 9042
#      protocol: TCP
#      targetPort: 9042
#  selector:
#    app: cassandra
#  sessionAffinity: None
#  type: ClusterIP
#status:
#  loadBalancer: {}